#include "Input.h"

FCaptureOnMousesDelegate LeftMouseDownDelegate;
FCaptureOnMousesDelegate LeftMouseUpDelegate;
FCaptureOnMousesDelegate RightMouseDownDelegate;
FCaptureOnMousesDelegate RightMouseUpDelegate;

FCaptureOnMousesWheelDelegate MouseWheelDelegate;

FCaptureOnMousesDelegate MouseMoveDelegate;