#pragma once

enum EMeshRenderLayerType
{
    RENDERLAYER_OPAQUE,
    RENDERLAYER_ALPHATEST,
    RENDERLAYER_TRANSPARENT,
    RENDERLAYER_POSTPROCESS,
    RENDERLAYER_BACKGROUND,
    RENDERLAYER_OPAQUEREFLECTOR,
};