#include "Input.h"

FCaptureOnMousesDelegate MouseDownDelegate;
FCaptureOnMousesDelegate MouseUpDelegate;

FCaptureOnMousesWheelDelegate MouseWheelDelegate;

FCaptureOnMousesDelegate MouseMoveDelegate;